/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package google.scrapper;

public class App {
    public static void main(String[] args) {
        MainBot bot = new MainBot("https://www.google.com/search?tbm=shop&hl=ja&psb=1&ved=2ahUKEwjKkfvApun8AhXECogJHdU4Bs0Qu-kFegQIABAK&q=pen&oq=pen&gs_lcp=Cgtwcm9kdWN0cy1jYxADUABYAGAAaABwAHgAgAEAiAEAkgEAmAEA&sclient=products-cc");
        bot.start();
    
    
        

    }
}
